### PR TITLE
[Easy] Exclude JIT orders from COW rewards

### PR DESCRIPTION
**Pull request by bh2smith**
Excluding JIT orders from COW rewards.

Cc @fleupold  for approval.

### CODE REVIEW

**Review by gentrexha — APPROVED** [review]

**Comment by josojo** [comment]
You mentioned last week that for some settlements, we don't find the settlements in the orderbook database. Is this impacting this PR?

**Comment by bh2smith** [comment]
> You mentioned last week that for some settlements, we don't find the settlements in the orderbook database. Is this impacting this PR?

There is still a bug with solver_competitions table but that doesn't affect this because we are fetching the data from only `settlements` and `trades` table. 

There is some commented code in the SQL file with details on the bug I will comment inline to show you.

**Review by gentrexha — APPROVED** [review]

**Comment by bh2smith** [comment]
@josojo - this is actually the content of #90

**Review by fleupold — APPROVED** [review]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2F3o7abB06u9bNzA8lu8%2Fgiphy.gif&token=lgtm" data-gitmeme-token="lgtm"></a>

**Pull request merged**
