### PR TITLE
3. Redirect: COW Rewards

### LINKED ISSUE #22: Cow Token Redirect by VouchRegistry
This task will be a 3 step process:

- [x] Query (#19)
Write a Dune query based on events emitted by [VouchRegistry](https://etherscan.io/address/0xb422f2520b0b7fd86f7da61b32cc631a59ed7e8f#code) to construct a unique mapping of valid `solver -> cowRewardsTarget` for which COW token rewards are to be redirected.
- [x] Fetch (#20)
Write a script that fetches the redirect data from Dune.
- [x] Redirect (#21)
Incorporate the Logic of redirecting COW rewards to the `cowRewardsTarget` specified by **valid** Vouches.

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #22

As part of the 3 step process this is the final PR introducing COW reward redirects. The script responsible for constructing the transfer file, intercepts any COW token transfers and replaces the `recipient` with the `reward_target` specified via `VouchRegistry`. You will notice that if there is nor specified redirect, the recipient is left as is (i.e. the solver itself).

To save gas, It would be possible to "consolidate" transfers of the same token to the same recipient by adding them up together. We have implemented transfer consolidation here.

# Test Plan

New tests introduced for transfer_consolidation

You can run this script for the current week:
```
python -m src.fetch.transfer_file --start '2022-05-03'
```

and find a very nice, compact transfer file like so:

```
token_type,token_address,receiver,amount
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x6C642caFCbd9d8383250bb25F67aE409147f78b2,208400.0
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x84dbAE2549d67CaF00f65C355de3D6F4df59A32C,11400.0
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x1e05EE95b8DfCB7C7567FA52e0ef47288b1C8Fb5,100.0
native,,0xdE1c59Bc25D806aD9DdCbe246c4B5e5505645718,16.592457156370344
native,,0xe92F359e6F05564849AFa933CE8F62b8007A1d5D,11.7596085198311
native,,0x77ec2A722c2393D3fD64617BBaF1499C713e616b,6.442125110455674
native,,0x15F4c337122Ec23859EC73Bec00aB38445E45304,6.040817305547322
native,,0x6fa201C3Aff9f1e4897Ed14c7326cF27548d9c35,3.6423891398067276
native,,0x2d15894FaC906386fF7f4Bd07fcEAc43fcF80C73,3.591885235391355
native,,0x833f076D182123cA8DDE2743045Ea02957bD61ef,1.0029895394093629
native,,0xe33062a24149f7801a48B2675Ed5111d3278F0f5,0.5298048853839988
native,,0xf2D21ad3c88170D4AE52bBBeBA80Cb6078D276F4,0.20823758681667942
native,,0x340185114F9D2617DC4c16088d0375D09fee9186,0.17059731234938455
native,,0xda324c2f06d3544E7965767ce9ca536dcb67a660,0.16418898218026148
native,,0xa97DEF4fBCBa3b646dd169Bc2eeE40f0f3fE7771,0.14136187546986229
native,,0x109BF9E0287Cc95cc623FBE7380dD841d4bdEb03,0.12877430090602068
native,,0xa0044c620Da7f2876dA7004719b8370eb7BE5e50,0.07676031139924357
native,,0xDe786877a10DBb7EBa25a4DA65aEcf47654F08ab,0.04139041774613465
native,,0xdAE69AffE582d36f330Ee1145995A53Fab670962,0.022778978282431278
native,,0x0d2584DA2F637805071f184bCFa1268eBAe8a24A,0.014079167989758732
native,,0x080a8b1E2f3695E179453c5e617b72A381BE44B9,0.013852816822931732
native,,0x1e05EE95b8DfCB7C7567FA52e0ef47288b1C8Fb5,0.00645199682930424
```

Note that numbers will change from now to when you run it.

### CODE REVIEW

**Review by josojo — COMMENTED** [review]
Looks good.

As you said the addition of transfers would be nice in order safe gas.

Also one could also incorporate the cow_redirects into the dune payout query directly, and not just "adapt the payout here". I think this would be a little bit cleaner, but its not a must for me.

**Comment by bh2smith** [comment]
I don't really want to incorporate that in the query because then I would have to paste the query into the transfer file query and it would become too large. I like having my hands on this information so that we can properly implement and test transfer consolidation. I would be willing to consider doing this at a later stage though if we think it might simplify things. But I would rather keeps the complicated queries separated (at least for now).


Also, I just realized, that we couldn't account for slippage the way we do if we already apply the redirects in the transfer file query.

**Review by josojo — APPROVED** [review]
Nice. works great. 

Here is the consolidated output file from 19-04
```
token_type,token_address,receiver,amount
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x6C642caFCbd9d8383250bb25F67aE409147f78b2,544500.0
native,,0xdE1c59Bc25D806aD9DdCbe246c4B5e5505645718,36.94022204530051
native,,0xe92F359e6F05564849AFa933CE8F62b8007A1d5D,23.607717275969815
native,,0x77ec2A722c2393D3fD64617BBaF1499C713e616b,19.01432406845195
native,,0x15F4c337122Ec23859EC73Bec00aB38445E45304,10.01364224324749
native,,0x2d15894FaC906386fF7f4Bd07fcEAc43fcF80C73,7.770317993171548
native,,0x833f076D182123cA8DDE2743045Ea02957bD61ef,6.903636495606964
native,,0xe33062a24149f7801a48B2675Ed5111d3278F0f5,1.7950292249334068
native,,0xda324c2f06d3544E7965767ce9ca536dcb67a660,0.6247024334269209
native,,0xf2D21ad3c88170D4AE52bBBeBA80Cb6078D276F4,0.5391477600443811
native,,0xDe786877a10DBb7EBa25a4DA65aEcf47654F08ab,0.49719949008315906
native,,0x340185114F9D2617DC4c16088d0375D09fee9186,0.350515350522078
native,,0xa97DEF4fBCBa3b646dd169Bc2eeE40f0f3fE7771,0.27026404223517303
native,,0xa0044c620Da7f2876dA7004719b8370eb7BE5e50,0.1848564611938275
native,,0x080a8b1E2f3695E179453c5e617b72A381BE44B9,0.16793160910787647
native,,0x0d2584DA2F637805071f184bCFa1268eBAe8a24A,0.1539708775006262
native,,0xdAE69AffE582d36f330Ee1145995A53Fab670962,0.13993168102699377
native,,0x8ccc61dBA297833dbe5D95FD6360f106b9A7576e,0.019392378159303208
```
Super smooth.


I would go for consolidation. But I am also happy to ask Anna one more time next week.

Note that for the upcoming payout there is "small error":
```
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x6C642caFCbd9d8383250bb25F67aE409147f78b2,208400.0
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x84dbAE2549d67CaF00f65C355de3D6F4df59A32C,11400.0
erc20,0xDEf1CA1fb7FBcDC777520aa7f396b4E015F497aB,0x1e05EE95b8DfCB7C7567FA52e0ef47288b1C8Fb5,100.0
native,,0xdE1c59Bc25D806aD9DdCbe246c4B5e5505645718,16.592457156370344
native,,0xe92F359e6F05564849AFa933CE8F62b8007A1d5D,11.7596085198311
native,,0x77ec2A722c2393D3fD64617BBaF1499C713e616b,6.442125110455674
native,,0x15F4c337122Ec23859EC73Bec00aB38445E45304,6.040817305547322
native,,0x6fa201C3Aff9f1e4897Ed14c7326cF27548d9c35,3.6423891398067276
native,,0x2d15894FaC906386fF7f4Bd07fcEAc43fcF80C73,3.591885235391355
native,,0x833f076D182123cA8DDE2743045Ea02957bD61ef,1.0029895394093629
native,,0xe33062a24149f7801a48B2675Ed5111d3278F0f5,0.5298048853839988
native,,0xf2D21ad3c88170D4AE52bBBeBA80Cb6078D276F4,0.20823758681667942
native,,0x340185114F9D2617DC4c16088d0375D09fee9186,0.17059731234938455
native,,0xda324c2f06d3544E7965767ce9ca536dcb67a660,0.16418898218026148
native,,0xa97DEF4fBCBa3b646dd169Bc2eeE40f0f3fE7771,0.14136187546986229
native,,0x109BF9E0287Cc95cc623FBE7380dD841d4bdEb03,0.12877430090602068
native,,0xa0044c620Da7f2876dA7004719b8370eb7BE5e50,0.07676031139924357
native,,0xDe786877a10DBb7EBa25a4DA65aEcf47654F08ab,0.04139041774613465
native,,0xdAE69AffE582d36f330Ee1145995A53Fab670962,0.022778978282431278
native,,0x0d2584DA2F637805071f184bCFa1268eBAe8a24A,0.014079167989758732
native,,0x080a8b1E2f3695E179453c5e617b72A381BE44B9,0.013852816822931732
native,,0x1e05EE95b8DfCB7C7567FA52e0ef47288b1C8Fb5,0.00645199682930424
```
0x1e05EE95b8DfCB7C7567FA52e0ef47288b1C8Fb5,100.0 was vouched in between, its just that now it is no longer. But I think we can live with this inaccuracy. We simply add to our rules that solver need the whole week.

But what we should improve in another PR: If a solver is vouched until Tuesday, and the scrip is executed on Wednesday, that then still the solver gets the payout. I think currently the script is dependent on the execution time. Sorry, I should have figured that earlier :)

**Comment by bh2smith** [comment]
Thanks @josojo 

Technically this is not an inaccuracy, this solver settled one batch and is not on the redirect list so they will receive 100 COW in the upcoming payout.


Screenshot 2022-05-06 at 4 17 19 PM


here is the batch: https://etherscan.io/tx/0x80f52baac0d2072fb8e30208ead0a3bb91998b11088c97127dcb4f5e0c4795ba

and this is exactly how our queries are expected to work. Unless you would like to introduce a block time parameter to the vouch query and redirect to the target address at the time the batch happened.

**Comment by bh2smith** [comment]
Note that adding block times to the vouching query will make it much much more complex...

**Comment by josojo** [comment]
>Note that adding block times to the vouching query will make it much much more complex...

I think if we just cut the vouch events until the tuesday of the payout, it's done. We don't have to be super precise, but I think it's valuable if the script is deterministic. It should not make a difference whether the script is run on tuesday or wednesday, if there are new vouch events between tuesday and wednesday

**Comment by bh2smith** [comment]
Make sense! Will do... later.

**Pull request merged**
