### PR TITLE
DB Migration Instructions

### LINKED ISSUE #296: Prod DB Migration
1. [x] Run migrations on prodDB (with ADMIN user)

```sh
docker run --add-host=host.docker.internal:host-gateway \
  --rm ghcr.io/cowprotocol/solver-rewards-db-migration \ 
  -url=jdbc:postgresql://$POSTGRES_HOST/$POSTGRES_DB \
  -user=$ADMIN_USER \
  -password=$ADMIN_PASSWORD \
  migrate
```

2. [x] Update `DB_URL` in Tenderly Deployment (using `R/W USER`): This will start populating from next settlement.
3. [x] Perform Export/Import on the relevant tables:
    - internalized_imbalances
    - settlement_simulations
    - settlements
    - tx_receipts

4. [ ] At this point, the prodDB is expected to be fully "synced", although we may want to check for missing data before proceeding with step 4. This can be achieved most simply by running the backfill script for the current date... Alternatively we could query the settlements table with the following Gap Detection Queries
    - [Dune](https://dune.com/queries/2481826)
    - LocalDB `select count(*) from settlements where block_number between {start_block} and {end_block};`

5. [x] Update `WAREHOUSE_URL` in dune-sync project with using `READONLY_USER`. This will need to be a Hotfix PR on the [infrastructure project](https://github.com/cowprotocol/infrastructure/). 
    - Done in https://github.com/cowprotocol/infrastructure/pull/436

## Additional Notes
- After step 1, we will not see any new data appearing in Dune until step 4 has been completed.
- Even if we don't bother with step 4, we can still recover from gaps later by backfilling (say the next day), then we would have to empty the Dune AWS Bucket and resync (from [dune-sync](https://github.com/cowprotocol/dune-sync) project:

    ```sh
    python -m src.scripts.empty_bucket --sync-table internal_imbalance
    ```

### PR DESCRIPTION
**Pull request by bh2smith**
Closes #296 

I have tried this out end to end and everything should run very smoothly. I expect this to take only about 5 minutes (with the exception of coordination of dune-sync deployment.

### CODE REVIEW

**Review by gentrexha — COMMENTED** [review]
I know you've said you've tried this. But is there a way for me to try this as well so I can confirm that?

**Comment by bh2smith** [comment]
> I know you've said you've tried this. But is there a way for me to try this as well so I can confirm that?

I am pretty sure you have access to all the secrets....  You could also create your own local instance of a postgres db and run all these instructions on your side. Is there something you feel you don't have here?

**Comment by bh2smith** [comment]
This migration was performed. Namely here is the backup import logs

<details><summary>Output</summary>

```
psql -h $DEST_HOST -U $DEST_WRITE_USER -d $DEST_DB -a -f ./backup.sql
Password for user solver_slippage_user: 
--
-- PostgreSQL database dump
--
-- Dumped from database version 13.7
-- Dumped by pg_dump version 15.3
SET statement_timeout = 0;
SET
SET lock_timeout = 0;
SET
SET idle_in_transaction_session_timeout = 0;
SET
SET client_encoding = 'UTF8';
SET
SET standard_conforming_strings = on;
SET
SELECT pg_catalog.set_config('search_path', '', false);
 set_config 
------------
 
(1 row)

SET check_function_bodies = false;
SET
SET xmloption = content;
SET
SET client_min_messages = warning;
SET
SET row_security = off;
SET
--
-- Data for Name: internalized_imbalances; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.internalized_imbalances (tx_hash, token, amount) FROM stdin;
COPY 69143
--
-- Data for Name: settlement_simulations; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.settlement_simulations (tx_hash, winning_settlement, complete, reduced) FROM stdin;
COPY 31713
--
-- Data for Name: settlements; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.settlements (block_number, log_index, solver, tx_hash) FROM stdin;
psql:backup.sql:239228: ERROR:  duplicate key value violates unique constraint "settlements_pkey"
DETAIL:  Key (block_number, log_index)=(17236905, 93) already exists.
CONTEXT:  COPY settlements, line 1
--
-- Data for Name: tx_receipts; Type: TABLE DATA; Schema: public; Owner: postgres
--
COPY public.tx_receipts (hash, block_number, processed, data) FROM stdin;
COPY 14399
--
-- PostgreSQL database dump complete
--
```
</details>

I will proceed in checking for gaps.

**Comment by bh2smith** [comment]
This has already been done. Merging without review.

**Pull request merged**
